/// Flutter icons Digimed_Icon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Digimed_Icon
///      fonts:
///       - asset: fonts/Digimed_Icon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DigimedIcon {
  DigimedIcon._();

  static const _kFontFam = 'DigimedIcon';
  static const String? _kFontPkg = null;

  static const IconData add_user = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_doctor = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_doctor = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pass = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laboratory = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_prsion_2 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData points = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exam = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData good = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData detail_user = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}