/// Flutter icons NotificationIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NotificationIcons
///      fonts:
///       - asset: fonts/NotificationIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NotificationIcons {
  NotificationIcons._();

  static const _kFontFam = 'NotificationIcons';
  static const String? _kFontPkg = null;

  static const IconData unread_notification = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData read_notification = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
