/// Flutter icons ToolsDimed
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ToolsDimed
///      fonts:
///       - asset: fonts/ToolsDimed.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ToolsDimed {
  ToolsDimed._();

  static const _kFontFam = 'IATools';
  static const String? _kFontPkg = null;

  static const IconData icon_tools =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digi_error_icon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
